apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cheesestripprefix
  namespace: cheese
spec:
  stripPrefix:
    prefixes:
      - /stilton
      - /cheddar
      - /wensleydale

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cheeses
  namespace: cheese
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`cheeses.kube`) && PathPrefix(`/stilton`)
    kind: Rule
    services:
    - name: stilton
      port: 80
    middlewares:
      - name: cheesestripprefix
  - match: Host(`cheeses.kube`) && PathPrefix(`/cheddar`)
    kind: Rule
    services:
    - name: cheddar
      port: 80 
    middlewares:
      - name: cheesestripprefix
  - match: Host(`cheeses.kube`) && PathPrefix(`/wensleydale`)
    kind: Rule
    services:
    - name: wensleydale
      port: 80 
    middlewares:
      - name: cheesestripprefix